# Generated by Django 4.1.5 on 2023-02-12 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=30, null=True)),
                ('contact', models.CharField(max_length=20)),
                ('adresse', models.TextField(max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1)),
                ('updated_by', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True, null=True)),
                ('statut', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('idpro', models.AutoField(primary_key=True, serialize=False)),
                ('nomprofil', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'profil',
            },
        ),
        migrations.CreateModel(
            name='Type_eau',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100)),
                ('pu', models.IntegerField()),
                ('qte', models.IntegerField()),
                ('qte_seuil', models.IntegerField()),
            ],
            options={
                'db_table': 'type_eau',
            },
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('idVille', models.AutoField(primary_key=True, serialize=False)),
                ('nomville', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'ville',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('contact', models.CharField(max_length=20)),
                ('idpro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ESSIVIVI_PROJECT.profil')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Info_livraison',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qte_livr', models.IntegerField()),
                ('montant', models.IntegerField()),
                ('bonus', models.IntegerField(default=0, null=True)),
                ('date_livr', models.DateTimeField(auto_now_add=True)),
                ('idcli', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ESSIVIVI_PROJECT.client')),
                ('idcom', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ESSIVIVI_PROJECT.user')),
                ('ideau', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ESSIVIVI_PROJECT.type_eau')),
            ],
            options={
                'db_table': 'info_livraison',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ESSIVIVI_PROJECT.user'),
        ),
        migrations.AddField(
            model_name='client',
            name='idVille',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ESSIVIVI_PROJECT.ville'),
        ),
    ]
